// ═════════════════════════════════════════════════════════════════════════════
// 灯塔 · 人效 —— 本地兜底数据
//
//   /lighthouse/people 未接通（或该接口报错）时，人效账本用这份数据渲染。
//   来源是人事《M4 月度绩效考评表》能源板块 / 通信板块两个文件，逐格照抄：
//     · 个人页填了收入 / 利润的，带同期与本期两组数，分数由引擎现算；
//     · 只在汇总表留了分数、个人页没有底表的，只给 serverScore 并打 noSource，
//       指标位一律画「—」—— 不允许拿一个来源不明的数字冒充实际业绩。
//   接口接通后 _loadPeople 自动改用服务端数据，这份不再参与渲染。
//
//   ⚠️ 生成物：人事表更新后重新导出，不要手改。
// ═════════════════════════════════════════════════════════════════════════════

import 'lighthouse_people.dart';

/// 考评月份（M4）。
const String kLhPeopleFallbackPeriod = '2026年4月';

final List<LhPeopleRow> kLhPeopleFallbackRows = <LhPeopleRow>[

  LhPeopleRow(
    id: '王一凡',
    name: '王一凡',
    group: '能源板块',
    role: '数字化解决方案架构师',
    sheetScore: null,
    sheetGrade: '汰',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '成品油零售',
        weight: 0.1429,
        template: LhPeopleTemplate.province,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: 'Fintech',
        weight: 0.1429,
        template: LhPeopleTemplate.province,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '平安-中石油（产险）',
        weight: 0.1429,
        template: LhPeopleTemplate.province,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '平安-中石油（非产险）',
        weight: 0.1429,
        template: LhPeopleTemplate.province,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '多渠道',
        weight: 0.1429,
        template: LhPeopleTemplate.province,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '平安-积分',
        weight: 0.1429,
        template: LhPeopleTemplate.province,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '平安-返费',
        weight: 0.1429,
        template: LhPeopleTemplate.province,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
    ],
  ),
  LhPeopleRow(
    id: '吕宙',
    name: '吕宙',
    group: '能源板块',
    role: '售前顾问',
    sheetScore: null,
    sheetGrade: '汰',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '平安（非产险）',
        weight: 0.5,
        template: LhPeopleTemplate.province,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '平安-产险',
        weight: 0.5,
        template: LhPeopleTemplate.province,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
    ],
  ),
  LhPeopleRow(
    id: '王轩',
    name: '王轩',
    group: '能源板块',
    role: '售前顾问',
    sheetScore: 71.42,
    sheetGrade: '危',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '内蒙古',
        weight: 0.6714,
        template: LhPeopleTemplate.province,
        revenue: 2355.73, prevRevenue: 2626.46,
        profit: 30.88, prevProfit: 31.25,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{},
      ),
      LhPeopleTask(
        name: '湖南',
        weight: 0.3286,
        template: LhPeopleTemplate.province,
        revenue: 1153.16, prevRevenue: 1266.65,
        profit: -1.2, prevProfit: 7.52,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{},
      ),
    ],
  ),
  LhPeopleRow(
    id: '石镇语',
    name: '石镇语',
    group: '能源板块',
    role: '',
    sheetScore: null,
    sheetGrade: '',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '陕西',
        weight: 0.3333,
        template: LhPeopleTemplate.province,
        revenue: 1023.66, prevRevenue: 938.66,
        profit: 7.44, prevProfit: 7.08,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 2, discountTotal: 2,
        flags: <LhPeopleFlag>{LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '河北',
        weight: 0.3333,
        template: LhPeopleTemplate.province,
        revenue: 1802.73, prevRevenue: 1628.42,
        profit: 2.1598, prevProfit: 2.0126,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '宁夏',
        weight: 0.3333,
        template: LhPeopleTemplate.province,
        revenue: 16.69, prevRevenue: 16.31,
        profit: -0.11, prevProfit: -0.12,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: true,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.badWeight},
      ),
    ],
  ),
  LhPeopleRow(
    id: '徐朝',
    name: '徐朝',
    group: '能源板块',
    role: '售前顾问',
    sheetScore: 68.0,
    sheetGrade: '汰',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '积分兑换',
        weight: 0.46,
        template: LhPeopleTemplate.province,
        revenue: 1004.21, prevRevenue: 2244.14,
        profit: 6.32, prevProfit: 17.08,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.badUnit},
      ),
      LhPeopleTask(
        name: '积分返费',
        weight: 0.47,
        template: LhPeopleTemplate.province,
        revenue: 1020.0, prevRevenue: 0.0,
        profit: 8.89, prevProfit: 0.0,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.zeroBase, LhPeopleFlag.badUnit},
      ),
      LhPeopleTask(
        name: '平安民营',
        weight: 0.07,
        template: LhPeopleTemplate.province,
        revenue: 113.62, prevRevenue: 173.87,
        profit: 0.84, prevProfit: 0.81,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.badUnit},
      ),
    ],
  ),
  LhPeopleRow(
    id: '王诗琪',
    name: '王诗琪',
    group: '能源板块',
    role: '售前顾问',
    sheetScore: null,
    sheetGrade: '汰',
    tasks: <LhPeopleTask>[

    ],
  ),
  LhPeopleRow(
    id: '石淼',
    name: '石淼',
    group: '通信板块',
    role: '数字化解决方案中心架构师',
    sheetScore: 0.0,
    sheetGrade: '汰',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '通信板块-小套出行会员',
        weight: 0.1667,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: 186.66,
        profit: null, prevProfit: 86.72,
        realUsers: null, prevRealUsers: 17.52,
        newUsers: null, prevNewUsers: 3.04,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.missingCurrent, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '小套-加油会员（湖北）',
        weight: 0.1667,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: 137.51,
        profit: null, prevProfit: 34.77,
        realUsers: null, prevRealUsers: 12.24,
        newUsers: null, prevNewUsers: 0.07,
        overdue: true,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.missingCurrent, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '小套-加油会员（江苏）',
        weight: 0.1667,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: 14.36,
        profit: null, prevProfit: 10.39,
        realUsers: null, prevRealUsers: 1.82,
        newUsers: null, prevNewUsers: 0.01,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.missingCurrent, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '小套-出行会员（广西）',
        weight: 0.1667,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: 109.59,
        profit: null, prevProfit: 55.72,
        realUsers: null, prevRealUsers: 11.14,
        newUsers: null, prevNewUsers: 2.79,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.missingCurrent, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '点播出行权益',
        weight: 1.0,
        template: LhPeopleTemplate.member,
        revenue: -17.21, prevRevenue: -15.42,
        profit: -17.21, prevProfit: -15.42,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: true,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{},
      ),
      LhPeopleTask(
        name: '浙江中石油',
        weight: 0.1667,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: 3417.0,
        profit: 5.12, prevProfit: 5.12,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.missingCurrent, LhPeopleFlag.badWeight},
      ),
    ],
  ),
  LhPeopleRow(
    id: '徐峥',
    name: '徐峥',
    group: '通信板块',
    role: '数字化解决方案高级专家',
    // 个人页没有底表，加权总分直接取汇总表
    serverScore: 0.0,
    sheetScore: 0.0,
    sheetGrade: '汰',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '小套-加油会员',
        weight: 0.3333,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '小套-加油会员（贵州）',
        weight: 0.3333,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '点播-AI豆商城',
        weight: 0.3333,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
    ],
  ),
  LhPeopleRow(
    id: '李同池',
    name: '李同池',
    group: '通信板块',
    role: '数字化解决方案高级专家',
    // 个人页没有底表，加权总分直接取汇总表
    serverScore: 60.09,
    sheetScore: 60.09,
    sheetGrade: '汰',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '陕西移动',
        weight: 0.6,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource},
      ),
      LhPeopleTask(
        name: '宁夏移动',
        weight: 0.3,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource},
      ),
      LhPeopleTask(
        name: '陕西中石油',
        weight: 0.1,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource},
      ),
    ],
  ),
  LhPeopleRow(
    id: '李钧庚',
    name: '李钧庚',
    group: '通信板块',
    role: '',
    sheetScore: null,
    sheetGrade: '',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '出行金',
        weight: 0.5,
        template: LhPeopleTemplate.member,
        revenue: 106.45, prevRevenue: 108.67,
        profit: 0.56, prevProfit: -2.56,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: 'Dict',
        weight: 0.5,
        template: LhPeopleTemplate.member,
        revenue: 88.71, prevRevenue: 0.0,
        profit: 84.96, prevProfit: -1.22,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.badWeight, LhPeopleFlag.zeroBase},
      ),
    ],
  ),
  LhPeopleRow(
    id: '石志华',
    name: '石志华',
    group: '通信板块',
    role: '数字化解决方案高级工程师',
    // 个人页没有底表，加权总分直接取汇总表
    serverScore: 51.46,
    sheetScore: 51.46,
    sheetGrade: '汰',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '小套-加油会员（吉林）',
        weight: 0.8305,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource},
        // 表内加权总分 47.0，除以权重还原成任务分
        serverScore: 56.5924,
      ),
      LhPeopleTask(
        name: '小套-好车主会员（吉林）',
        weight: 0.1695,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource},
        // 表内加权总分 4.46，除以权重还原成任务分
        serverScore: 26.3127,
      ),
    ],
  ),
  LhPeopleRow(
    id: '何佳伟',
    name: '何佳伟',
    group: '通信板块',
    role: '高级售前顾问',
    // 个人页没有底表，加权总分直接取汇总表
    serverScore: 57.05,
    sheetScore: 57.05,
    sheetGrade: '汰',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '广东中石油',
        weight: 0.3,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 2, discountTotal: 4,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource},
      ),
      LhPeopleTask(
        name: '中油bp',
        weight: 0.08,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource},
      ),
      LhPeopleTask(
        name: '成品油sass',
        weight: 0.12,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource},
      ),
      LhPeopleTask(
        name: '小套-加油会员（广东）',
        weight: 0.5,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource},
      ),
    ],
  ),
  LhPeopleRow(
    id: '叶锦成',
    name: '叶锦成',
    group: '通信板块',
    role: '高级售前顾问',
    // 个人页没有底表，加权总分直接取汇总表
    serverScore: 97.78,
    sheetScore: 97.78,
    sheetGrade: '优',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '小套-出行会员（贵州）',
        weight: 1.0,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource},
      ),
    ],
  ),
  LhPeopleRow(
    id: '吕杰',
    name: '吕杰',
    group: '通信板块',
    role: '高级售前顾问',
    // 个人页没有底表，加权总分直接取汇总表
    serverScore: 91.01,
    sheetScore: 91.01,
    sheetGrade: '良',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '小套-加油会员（天津）',
        weight: 0.5,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '点播-加油会员（北京）',
        weight: 0.5,
        template: LhPeopleTemplate.member,
        revenue: null, prevRevenue: null,
        profit: null, prevProfit: null,
        realUsers: null, prevRealUsers: null,
        newUsers: null, prevNewUsers: null,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.noSource, LhPeopleFlag.badWeight},
      ),
    ],
  ),
  LhPeopleRow(
    id: '曾辉景',
    name: '曾辉景',
    group: '通信板块',
    role: '',
    sheetScore: null,
    sheetGrade: '',
    tasks: <LhPeopleTask>[
      LhPeopleTask(
        name: '江苏中石油',
        weight: 0.5,
        template: LhPeopleTemplate.member,
        revenue: 1243.1686, prevRevenue: 1408.1091,
        profit: -2.4348, prevProfit: -2.9799,
        realUsers: 4.1439, prevRealUsers: 4.6937,
        newUsers: 1.3813, prevNewUsers: 1.5646,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.badWeight},
      ),
      LhPeopleTask(
        name: '江苏移动',
        weight: 0.5,
        template: LhPeopleTemplate.member,
        revenue: 30.32, prevRevenue: 28.96,
        profit: 21.8, prevProfit: 23.07,
        realUsers: 2.47, prevRealUsers: 2.72,
        newUsers: 0.34, prevNewUsers: 0.04,
        overdue: false,
        discountAchieved: 1, discountTotal: 1,
        flags: <LhPeopleFlag>{LhPeopleFlag.badWeight},
      ),
    ],
  ),
  LhPeopleRow(
    id: '欧阳巍',
    name: '欧阳巍',
    group: '通信板块',
    role: '高级售前顾问',
    // 个人页没有底表，加权总分直接取汇总表
    serverScore: 90.0,
    sheetScore: 90.0,
    sheetGrade: '良',
    tasks: <LhPeopleTask>[

    ],
  ),
  LhPeopleRow(
    id: '陆青',
    name: '陆青',
    group: '通信板块',
    role: '售前顾问',
    // 个人页没有底表，加权总分直接取汇总表
    serverScore: 87.2,
    sheetScore: 87.2,
    sheetGrade: '良',
    tasks: <LhPeopleTask>[

    ],
  ),
];
