"""Freeze the preview's Windows Chromium emoji artwork for every APP platform.

Run from the Flutter root: python tool/export_im_egg_assets.py
Uses an isolated headless Chrome profile; no user browser profile is accessed.
"""
import base64
import html
import json
from pathlib import Path
import re
import subprocess
import shutil

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'assets/images/im_eggs'
WORK = ROOT / '.dart_tool/im_egg_export'
CHROME = Path('C:/Program Files/Google/Chrome/Application/chrome.exe')
GLYPHS = list(dict.fromkeys('🎂 🍰 🧁 🧧 ✨ 💰 🎆 🎉 🎊 🌕 🐇 🥮 ❄️ ⭐ 🎄 🌱 🌼 💚 💜 💫 🫶 🎓 🌈 🎁 ☀️ 💝 🌿 🌍 🎈 💐 🎃 🎅'.split()))


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    WORK.mkdir(parents=True, exist_ok=True)
    # This is the font stack in app_easter_eggs_preview.html, not Flutter's
    # device-dependent emoji fallback. The exported pixels are bundled assets.
    document = '''<!doctype html><meta charset="utf-8"><pre id="result"></pre>
    <script>
    const result = [];
    for (const glyph of GLYPHS) {
      const c = document.createElement('canvas');
      const ctx = c.getContext('2d');
      const font = '128px -apple-system, BlinkMacSystemFont, "SF Pro Display", "PingFang SC", "Microsoft YaHei", sans-serif';
      ctx.font = font;
      const m = ctx.measureText(glyph);
      const width = Math.ceil(m.width);
      c.width = width + 64; c.height = 192;
      ctx.font = font; ctx.textBaseline = 'alphabetic';
      const ascent = m.fontBoundingBoxAscent;
      const descent = m.fontBoundingBoxDescent;
      ctx.fillText(glyph, 32, 32 + (128 - ascent - descent) / 2 + ascent);
      result.push({glyph, width, png:c.toDataURL('image/png').split(',')[1]});
    }
    document.getElementById('result').textContent = JSON.stringify(result);
    </script>'''.replace('GLYPHS', json.dumps(GLYPHS, ensure_ascii=False))
    page = WORK / 'export.html'
    page.write_text(document, encoding='utf-8')
    process = subprocess.run([
        str(CHROME), '--headless=new', '--no-first-run', '--disable-gpu',
        '--disable-extensions', '--dump-dom',
        '--user-data-dir=' + str(WORK / 'profile'), page.as_uri(),
    ], capture_output=True, timeout=60)
    dom = process.stdout.decode('utf-8')
    match = re.search(r'<pre id="result">(.*?)</pre>', dom, re.S)
    if not match:
        raise RuntimeError('Chrome did not return emoji artwork: ' + process.stderr.decode('utf-8', errors='replace')[-1000:])
    records = json.loads(html.unescape(match.group(1)))
    manifest = {}
    for record in records:
        filename = '_'.join(format(ord(c), 'x') for c in record['glyph']) + '.png'
        (OUTPUT / filename).write_bytes(base64.b64decode(record['png']))
        manifest[record['glyph']] = {'file': filename, 'width': record['width'], 'em': 128, 'padding': 32}
    (OUTPUT / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding='utf-8')
    # Also consumed by the HTML preview, so both render the very same files.
    (OUTPUT / 'manifest.js').write_text('window.imEggArtwork = ' + json.dumps(manifest, ensure_ascii=False) + ';\n', encoding='utf-8')
    dart = '// Generated by tool/export_im_egg_assets.py.\n'
    dart += 'const imEggArtworkSpecs = <String, (String, double)>{\n'
    for glyph, item in manifest.items():
        dart += f"  '{glyph}': ('assets/images/im_eggs/{item['file']}', {item['width']}.0),\n"
    dart += '};\n'
    (ROOT / 'lib/features/chat/im_egg_artwork_specs.dart').write_text(dart, encoding='utf-8')
    admin_assets = ROOT.parent / 'admin-web/src/assets/im-eggs'
    if admin_assets.parent.parent.exists():
        admin_assets.mkdir(parents=True, exist_ok=True)
        for item in manifest.values():
            shutil.copy2(OUTPUT / item['file'], admin_assets / item['file'])
        shutil.copy2(OUTPUT / 'manifest.json', admin_assets / 'manifest.json')
    print(f'Exported {len(records)} preview glyphs to {OUTPUT}')


if __name__ == '__main__':
    main()
